name: PlateRates
description: The place to be for sharing and rating delicious food creations.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.2.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated/pub.dev/android_package_installer-0.0.2/ by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  http: ^1.1.0
  flutter_secure_storage: ^9.2.2
  flutter_rating_bar: ^4.0.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.7
  camera: ^0.11.0+2
  path_provider: ^2.0.15
  image: ^4.0.17
  toggle_switch: ^2.1.0
  json_cache: ^4.0.0
  shared_preferences: ^2.2.0
  flutter_phoenix: ^1.1.1
  package_info_plus: ^8.0.2
  camera_web: ^0.3.1+4
  url_launcher: ^6.1.12
  file_selector: ^1.0.0
  flutter_linkify: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #install_plugin: ^2.1.0
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  flutter_local_notifications: ^17.2.2
  #flutter_chat_ui: ^1.6.9
  web_socket_channel: ^3.0.1
  intl: ^0.19.0
  flutter_flavor: ^3.1.3
  permission_handler: ^11.0.1
  firebase_crashlytics: ^4.1.0
  firebase_app_check: ^0.3.1
  open_file: ^3.3.2
  #flutter_downloader: ^1.11.4
  app_installer: ^1.1.0
  font_awesome_flutter: ^10.6.0
  chatview: ^2.2.0
  dart_jsonwebtoken: ^2.14.0
  rename_app: ^1.3.2
  flutter_app_badger: ^1.5.0
  flutter_image_compress: ^2.3.0
  #google_sign_in: ^6.1.5
  #android_package_installer: ^0.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  image_path_android: "assets/icons/platerates-logo.png"
  image_path_ios: "assets/icons/platerates-logo.png"
  android: true
  ios: false
  image_path: "assets/icons/platerates-logo.png"
  min_sdk_android: 33 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/platerates-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/platerates-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/icons/platerates-logo.png"
#flutter pub run flutter_launcher_icons

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
